In [23]:
# Read the csv file
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objs as go

#input_file_path ="../data/Data_for_Project.csv " 
#input_file_path ="C:\Users\Lenovo\Documents\GitHub\ELO-Data-Analysis-Project-Level-of-Happiness\data\Data_for_Project.csv" 
df= pd.read_csv("../../data/Data_for_Project.csv", delimiter=';')
df.head()

,Country name,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom Index,The World Giving Index,Corruption Perceptions Index
0,Afghanistan,"1,859","7,324","0,341","53,95","3,82",20.0,24
1,Albania,"5,277","9,567","0,718","69,08","7,67",28.0,36
2,Algeria,"5,329","9,3","0,855","66,39","4,82",32.0,33
3,Argentina,"6,024","9,959","0,891","67,13","6,85",36.0,38
4,Armenia,"5,342","9,615","0,79","67,12","7,99",28.0,46

## Data Cleaning

In [24]:
print(df.info())

# Drop rows where all elements are missing
df.dropna(how='all', inplace=True)

# Fill missing values using forward fill method
df.fillna(method='ffill', inplace=True)

# Columns to be converted from string to numeric
columns_to_convert = ['Ladder score', 'Logged GDP per capita', 'Social support', 
                      'Healthy life expectancy', 'Freedom Index', 'The World Giving Index', 
                      'Corruption Perceptions Index']

# Replace commas with dots and convert to numeric
df[columns_to_convert] = df[columns_to_convert].replace({',': '.'}, regex=True)
df[columns_to_convert] = df[columns_to_convert].astype(float)

# Display the first few rows and information about the dataset after cleaning
print(df.head())
print(df.info())

# Save the cleaned data to a new CSV file
output_file_path ="../../data/Cleaned_Data_for_Project.csv" 
#output_file_path = "data/Cleaned_Data_for_Project.csv"
df.to_csv(output_file_path, index=False, sep=';')

print(f"Data has been saved to the file {output_file_path}")
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country name                  136 non-null    object
 1   Ladder score                  136 non-null    object
 2   Logged GDP per capita         136 non-null    object
 3   Social support                136 non-null    object
 4   Healthy life expectancy       135 non-null    object
 5   Freedom Index                 136 non-null    object
 6   The World Giving Index        135 non-null    float64
 7   Corruption Perceptions Index  136 non-null    int64
dtypes: float64(1), int64(1), object(6)
memory usage: 8.6+ KB
None
  Country name  Ladder score  Logged GDP per capita  Social support  \
0  Afghanistan         1.859                  7.324           0.341
1      Albania         5.277                  9.567           0.718
2      Algeria         5.329                  9.300           0.855
3    Argentina         6.024                  9.959           0.891
4      Armenia         5.342                  9.615           0.790

   Healthy life expectancy  Freedom Index  The World Giving Index  \
0                    53.95           3.82                    20.0
1                    69.08           7.67                    28.0
2                    66.39           4.82                    32.0
3                    67.13           6.85                    36.0
4                    67.12           7.99                    28.0

   Corruption Perceptions Index
0                          24.0
1                          36.0
2                          33.0
3                          38.0
4                          46.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country name                  136 non-null    object
 1   Ladder score                  136 non-null    float64
 2   Logged GDP per capita         136 non-null    float64
 3   Social support                136 non-null    float64
 4   Healthy life expectancy       136 non-null    float64
 5   Freedom Index                 136 non-null    float64
 6   The World Giving Index        136 non-null    float64
 7   Corruption Perceptions Index  136 non-null    float64
dtypes: float64(7), object(1)
memory usage: 8.6+ KB
None
Data has been saved to the file ../../data/Cleaned_Data_for_Project.csv
  Country name  Ladder score  Logged GDP per capita  Social support  \
0  Afghanistan         1.859                  7.324           0.341
1      Albania         5.277                  9.567           0.718
2      Algeria         5.329                  9.300           0.855
3    Argentina         6.024                  9.959           0.891
4      Armenia         5.342                  9.615           0.790

   Healthy life expectancy  Freedom Index  The World Giving Index  \
0                    53.95           3.82                    20.0
1                    69.08           7.67                    28.0
2                    66.39           4.82                    32.0
3                    67.13           6.85                    36.0
4                    67.12           7.99                    28.0

   Corruption Perceptions Index
0                          24.0
1                          36.0
2                          33.0
3                          38.0
4                          46.0

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_484\3007397944.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [25]:
# Loading the saved dataset
df1 = pd.read_csv("../../data/Cleaned_Data_for_Project.csv", sep=';')

# Print unique values of country names
unique_countries = df1['Country name'].unique()
print(unique_countries)

['Afghanistan' 'Albania' 'Algeria' 'Argentina' 'Armenia' 'Australia'
 'Austria' 'Bahrain' 'Bangladesh' 'Belgium' 'Benin' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Bulgaria' 'Burkina Faso'
 'Cambodia' 'Cameroon' 'Canada' 'Chad' 'Chile' 'China' 'Colombia'
 'Comoros' 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica' 'Croatia'
 'Cyprus' 'Czechia' 'Denmark' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Estonia' 'Ethiopia' 'Finland' 'France' 'Gabon' 'Gambia'
 'Georgia' 'Germany' 'Ghana' 'Greece' 'Guatemala' 'Guinea' 'Honduras'
 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel'
 'Italy' 'Ivory Coast' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kosovo' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Liberia' 'Lithuania'
 'Luxembourg' 'Madagascar' 'Malawi' 'Malaysia' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'Netherlands' 'New Zealand'
 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway' 'Pakistan'
 'Panama' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal' 'Romania'
 'Russia' 'Saudi Arabia' 'Senegal' 'Serbia' 'Sierra Leone' 'Singapore'
 'Slovakia' 'Slovenia' 'South Africa' 'South Korea' 'Spain' 'Sri Lanka'
 'State of Palestine' 'Sweden' 'Switzerland' 'Taiwan Province of China'
 'Tajikistan' 'Tanzania' 'Thailand' 'Togo' 'Tunisia' 'Türkiye' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'United States'
 'Uruguay' 'Uzbekistan' 'Venezuela' 'Vietnam' 'Zambia' 'Zimbabwe']